project:
    version: @project.version@

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/test_system
#        username: yourusername
#        password: yourpassword
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

flyway:
    url: jdbc:postgresql://localhost:5432/yourdatabase
    user: yourusername
    password: yourpassword
    locations: classpath:db/migration

